name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & build frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build -- --base-href /

      - name: Deploy to Cloudflare Pages via Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy frontend/dist/campus-study-buddy/browser --project-name=studynester
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
