name: Full Stack Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    name: Angular Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      # Optional but helpful: ensure CI flags are set so Jest never tries watch mode, etc.
      - name: Run frontend tests with coverage
        env:
          CI: 'true'
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: npm run test:coverage

      - name: Upload HTML coverage as artifact (optional)
        uses: actions/upload-artifact@v5
        with:
          name: frontend-coverage-html
          path: frontend/coverage
          if-no-files-found: error
          retention-days: 7

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: frontend/coverage/lcov.info
          name: frontend
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  backend-tests:
    name: NestJS Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests with coverage
        run: npm run test:cov

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: backend/coverage/lcov.info
          flags: backend
          name: backend
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
